kind: pipeline
name: default
steps:
- name: info 
  commands:
  - echo "AAAA"
- name: test
  image: maven:3-jdk-10
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
