kind: pipeline 

steps:

- name: Servers
  image: alpine
  commands:
    - ls
    - cd ventas/target
    - ls
    - apk add curl     
    - curl -v -u admin:123 -T ventas-0.0.1-SNAPSHOT.war 'ttp://nklvsbit7y0xh01yywqvch.webrelay.io/manager/text/deploy?path=/my-app-path&update=true'
- name: notify
  image: drillster/drone-email
  settings:
    from: chavarria181386@unis.edu.gt    
    host: smtp.sendgrid.net
    port: 465
    username:
       from_secret: emu1
    password: 
      from_secret: emu2
     
    
    recipients:
        - gchavarriamunoz@gmail.com
    when:
      status:
      - failure

    
    
