kind: pipeline 

steps:

- name: Build-dev
  image: maven:3-jdk-11
  commands:  
    - mvn -f ventas/target -Pdev package
  when:
    branch:
      -dev
- name: Build-uat
  image: maven:3-jdk-11
  commands:  
    - mvn -f ventas/target -Puat package
  when:
    branch:
      -dev

- name: Build-prod
  image: maven:3-jdk-11
  commands:  
    - mvn -f ventas/target -Pprod package
  when:
    branch:
      -prod

- name: Build-main
  image: maven:3-jdk-11
  commands:  
    - mvn -f ventas/target -Pprod package
  when:
    branch:
      -main
     
      

- name: Servers-dev
  image: alpine
  commands:
    - ls
    - cd ventas/target
    - ls
    - apk add curl
    - mv  ventas-0.0.1-SNAPSHOT.war main.war
    - curl -v -u admin:admin -T main.war 'http://j6oc0tsmiw4dohyjwum5a5.webrelay.io//manager/text/deploy?path=/main-dev&update=true'
  when:
    branch:
      -dev


- name: Servers-uat
  image: alpine
  commands:
    - ls
    - cd ventas/target
    - ls
    - apk add curl
    - mv  ventas-0.0.1-SNAPSHOT.war main.war
    - curl -v -u admin:admin -T main.war 'http://j6oc0tsmiw4dohyjwum5a5.webrelay.io//manager/text/deploy?path=/main-uat&update=true'
  when:
    branch:
      -uat

- name: Servers-prod
  image: alpine
  commands:
    - ls
    - cd ventas/target
    - ls
    - apk add curl
    - mv  ventas-0.0.1-SNAPSHOT.war main.war
    - curl -v -u admin:admin -T main.war 'http://j6oc0tsmiw4dohyjwum5a5.webrelay.io//manager/text/deploy?path=/main-prod&update=true'
  when:
    branch:
      -prod
      
- name: Servers-main
  image: alpine
  commands:
    - ls
    - cd ventas/target
    - ls
    - apk add curl
    - mv  ventas-0.0.1-SNAPSHOT.war main.war
    - curl -v -u admin:admin -T main.war 'http://j6oc0tsmiw4dohyjwum5a5.webrelay.io//manager/text/deploy?path=/main-prodmain&update=true'
  when:
    branch:
      -main



    



- name: notify
  image: drillster/drone-email
  settings:
    from: chavarria181386@unis.edu.gt    
    host: smtp.sendgrid.net
    port: 465
    username:
       from_secret: emu1
    password: 
      from_secret: emu2    
    
    recipients:
        - gchavarriamunoz@gmail.com

  when:
    status:
    - success
    - failure
 

    
    
