kind: pipeline 

steps:
- name: notify
  image: drillster/drone-email
  settings:
    from: marcelinos777@gmail.com  
    host: smtp.gmail.com
    username:
       from_secret: EMAIL_USERNAME
    password: 
      from_secret: EMAIL_PASSWORD
     
    
    recipients:
        - chavarria181386@unis.edu.gt
- name: Servers
  image: alpine
  commands:
    - ls
    - cd ventas/target
    - ls
    - apk add curl     
    - curl -v -u admin:123 -T ventas-0.0.1-SNAPSHOT.war 'ttp://nklvsbit7y0xh01yywqvch.webrelay.io/manager/text/deploy?path=/my-app-path&update=true'


    
    
