kind: pipeline
name: Integration
steps:
- name: build-war
  image: maven:3-jdk-11
  commands:
    - mvn -f ventas/pom.xml package 
- name: Servers
  image: alpine
  commands:
    - ls
    - de ventas/target
       


   
   
