kind: pipeline
type: docker
name: Integration


steps:
- name: build-war
  image: maven:3-jdk-11
  commands:
    - mvn -f ventas/pom.xml package 
- name: Servers
  image: alpine
  commands:
    - ls
    - cd ventas/target
    - ls  
    - apk add curl
    - docker cp main-dev.war tomcat1:/usr/local/tomcat/webappsa
    
    
    


   
   
