kind: pipeline 
type: docker
platform:
  os: linux
  arch: amd64


steps:


- name: UnitTest
  image: maven:3-jdk-11
  commands:    
    - mvn -f ventas/pom.xml test
  when:
    event:
      include:     
      - pull_request

- name: notify-unit-test 
  image: drillster/drone-email
  settings:
    from: chavarria181386@unis.edu.gt    
    host: smtp.sendgrid.net
    port: 465
    username:
      from_secret: emu1
    password: 
      from_secret: emu2 
    recipients:
      - gchavarriamunoz@gmail.com
      - jflores@unis.edu.gt
    body: Error en la pipeline;Los unit test fallaron 
    attachment: build-result.xml
  when:
    event:
      include:     
      - pull_request
    status:      
    - failure


- name: Sonarqube-analisis 
  image: maven:3-jdk-11
  commands:
    - mvn -f ventas/pom.xml clean verify sonar:sonar -Dmaven.test.skip=true -Dsonar.login=admin -Dsonar.password=tzec99 -Dsonar.host.url=http://a2c2-2803-d100-e520-54f-e822-6d15-8c57-2209.ngrok.io 
  when:
    event:
      include:     
      - pull_request

- name: Quality-Gate
  image: maven:3-jdk-11
  commands:
    - mvn -f ventas/pom.xml  clean verify sonar:sonar sonar-quality-gate:check -Dsonar.login=admin -Dsonar.password=tzec99 -Dsonar.host.url=http://a2c2-2803-d100-e520-54f-e822-6d15-8c57-2209.ngrok.io 
  when:
    event:
      include:     
      - pull_request

- name: notify-sonar-q
  image: drillster/drone-email
  settings:
    from: chavarria181386@unis.edu.gt    
    host: smtp.sendgrid.net
    port: 465
    username:
      from_secret: emu1
    password: 
      from_secret: emu2    
    
    recipients:
        - gchavarriamunoz@gmail.com
        - jflores@unis.edu.gt
    body: Error en la pipeline; El analisis sonarq indica que no pasa las quality gates 
    attachment: build-result.xml
  when:
    event:
      include:     
      - pull_request
    status:      
    - failure

- name: Build-dev
  image: maven:3-jdk-11
  commands:  
    - mvn -f ventas/pom.xml -Dspring.profiles.active=dev clean  install
  when:
    branch:
      - DEV
    event:
      include:
      - push
    
 
- name: Build-uat
  image: maven:3-jdk-11
  commands:  
    - mvn -f ventas/pom.xml -Dspring.profiles.active=uat clean install
  when:
    branch:
      - UAT
    event:
      include:
      - push
   

- name: Build-prod
  image: maven:3-jdk-11
  commands:  
    - mvn -f ventas/pom.xml -Dspring.profiles.active=prod clean install
  when:
    branch:
      - 1PROD
    event:
      include:
      - push
     
      
- name: Build-main
  image: maven:3-jdk-11
  commands:  
    - mvn -f ventas/pom.xml -Dspring.profiles.active=prod clean install
    
  when:
    branch:
      - main
    event:
      include:
      - push
    
     
- name: Servers-dev
  image: alpine
  commands:
    - ls
    - cd /drone/src/ventas/target/
    - ls
    - apk add curl
    - stat ventas-0.0.1-SNAPSHOT.war
    - mv  ventas-0.0.1-SNAPSHOT.war main.war
    - curl -v -u admin:admin -T main.war 'http://1rzzy5jihajnmxkmecxhe4.webrelay.io/manager/text/deploy?path=/main-dev&update=true'
  when:
    branch:
      - DEV
    event:
      include:
      - push

   
- name: Servers-uat
  image: alpine
  commands:
    - ls
    - cd /drone/src/ventas/target/
    - ls
    - apk add curl
    - stat ventas-0.0.1-SNAPSHOT.war
    - mv  ventas-0.0.1-SNAPSHOT.war main.war  
    - curl -v -u admin:admin -T main.war 'http://1rzzy5jihajnmxkmecxhe4.webrelay.io/manager/text/deploy?path=/main-uat&update=true'
  when:
    branch:
      - UAT
    event:
      include:
      - push
 
- name: Servers-prod
  image: alpine
  commands:
    - ls
    - cd /drone/src/ventas/target/
    - ls
    - apk add curl
    - stat ventas-0.0.1-SNAPSHOT.war
    - mv  ventas-0.0.1-SNAPSHOT.war main.war
    - curl -v -u admin:admin -T main.war 'http://1rzzy5jihajnmxkmecxhe4.webrelay.io/manager/text/deploy?path=/main-prod&update=true'
  when:
    branch:
      - 1PROD
    event:
      include:
      - push
  
     
- name: Servers-main
  image: alpine
  commands:
    - ls
    - cd /drone/src/ventas/target/
    - ls
    - apk add curl
    - stat ventas-0.0.1-SNAPSHOT.war
    - mv  ventas-0.0.1-SNAPSHOT.war main.war
    - curl -v -u admin:admin -T main.war 'http://1rzzy5jihajnmxkmecxhe4.webrelay.io/manager/text/deploy?path=/main-prodmain&update=true'
  when:
    branch:
      - main
    
    event:
      include:
      - push
   

- name: Notifiación-final
  image: drillster/drone-email
  settings:
    from: chavarria181386@unis.edu.gt    
    host: smtp.sendgrid.net
    port: 465
    username:
      from_secret: emu1
    password: 
      from_secret: emu2    
    subject: status pipeline 
    recipients:
        - gchavarriamunoz@gmail.com
        - jflores@unis.edu.gt
    attachment: build-result.xml
  when:
    event:
      include:     
      - push
    status:      
    - failure
    - success
    branch:
    - main
    - DEV
    - UAT
    - 1PROD
 


- name: notificación-slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack  
    channel: drone
    template: >
      {{#success build.status}}
        build {{build.number}} Exito la pipeline se ejecuto correctamente.
      {{else}}
        build {{build.number}} fallo el build . Revisar ejecucion pipeline.
      {{/success}}
  when:
    status:      
    - failure
    - success
