kind: pipeline 
name: Springboot

steps:
- name: UnitTest
  image: maven:3-jdk-11
  commands:    
    - mvn -f ventas/pom.xml test
  when:
    event:
      include:     
      - pull_request

- name: notify-unit-test 
  image: drillster/drone-email
  settings:
    from: chavarria181386@unis.edu.gt    
    host: smtp.sendgrid.net
    port: 465
    username:
      from_secret: emu1
    password: 
      from_secret: emu2 
    recipients:
      - gchavarriamunoz@gmail.com
      - jflores@unis.edu.gt
    body: Los unit test fallaron 
    attachment: build-result.xml
  when:
    event:
      include:     
      - pull_request
    status:      
    - failure


- name: Sonarqube-analisis 
  image: maven:3-jdk-11
  commands:
    - mvn -f ventas/pom.xml clean verify sonar:sonar -Dsonar.login=admin -Dsonar.password=tzec99 -Dsonar.host.url=http://cc5c-45-229-42-199.ngrok.io 
  when:
    event:
      include:     
      - pull_request



- name: Quality-Gate
  image: maven:3-jdk-11
  commands:
    - mvn clean verify sonar:sonar sonar-quality-gate:check -Dsonar.login=admin -Dsonar.password=tzec99 -Dsonar.host.url=http://cc5c-45-229-42-199.ngrok.io 
  when:
    event:
      include:     
      - pull_request

- name: notify-sonar-q
  image: drillster/drone-email
  settings:
    from: chavarria181386@unis.edu.gt    
    host: smtp.sendgrid.net
    port: 465
    username:
      from_secret: emu1
    password: 
      from_secret: emu2    
    
    recipients:
        - gchavarriamunoz@gmail.com
        - jflores@unis.edu.gt
    body: El analisis sonarq indica que no pasa las quality gates 
    attachment: build-result.xml
  when:
    event:
      include:     
      - pull_request
    status:      
    - failure






- name: Build-dev
  image: maven:3-jdk-11
  commands:  
    - mvn -f ventas/pom.xml -Dspring.profiles.active=dev clean  install
  when:
    branch:
      - DEV
    event:
      include:
      - push
    
  
- name: Build-uat
  image: maven:3-jdk-11
  commands:  
    - mvn -f ventas/pom.xml -Dspring.profiles.active=uat clean install
  when:
    branch:
      - UAT
    event:
      include:
      - push
   


- name: Build-prod
  image: maven:3-jdk-11
  commands:  
    - mvn -f ventas/pom.xml -Dspring.profiles.active=prod clean install
  when:
    branch:
      - 1PROD
    event:
      include:
      - push
     
      
- name: Build-main
  image: maven:3-jdk-11
  commands:  
    - mvn -f ventas/pom.xml -Dspring.profiles.active=prod clean install
    
  when:
    branch:
      - main
    event:
      include:
      - push
   
    
      
- name: Servers-dev
  image: alpine
  commands:
    - ls
    - cd /drone/src/ventas/target/
    - ls
    - apk add curl
    - stat ventas-0.0.1-SNAPSHOT.war
    - mv  ventas-0.0.1-SNAPSHOT.war main.war
    - curl -v -u admin:admin -T main.war 'http://wzcvu06han7aiqu3qovebi.webrelay.io/manager/text/deploy?path=/main-dev&update=true'
  when:
    branch:
      - DEV
    event:
      include:
      - push
    
    
- name: Servers-uat
  image: alpine
  commands:
    - ls
    - cd /drone/src/ventas/target/
    - ls
    - apk add curl
    - stat ventas-0.0.1-SNAPSHOT.war
    - mv  ventas-0.0.1-SNAPSHOT.war main.war  
    - curl -v -u admin:admin -T main.war 'http://wzcvu06han7aiqu3qovyj5.webrelay.io/manager/text/deploy?path=/main-uat&update=true'
  when:
    branch:
      - UAT
    event:
      include:
      - push
 


- name: Servers-prod
  image: alpine
  commands:
    - ls
    - cd /drone/src/ventas/target/
    - ls
    - apk add curl
    - stat ventas-0.0.1-SNAPSHOT.war
    - mv  ventas-0.0.1-SNAPSHOT.war main.war
    - curl -v -u admin:admin -T main.war 'http://wzcvu06han7aiqu3qovyj5.webrelay.io/manager/text/deploy?path=/main-prod&update=true'
  when:
    branch:
      - 1PROD
    event:
      include:
      - push
  
      
- name: Servers-main
  image: alpine
  commands:
    - ls
    - cd /drone/src/ventas/target/
    - ls
    - apk add curl
    - stat ventas-0.0.1-SNAPSHOT.war
    - mv  ventas-0.0.1-SNAPSHOT.war main.war
    - curl -v -u admin:admin -T main.war 'http://wzcvu06han7aiqu3qovyj5.webrelay.io/manager/text/deploy?path=/main-prodmain&update=true'
  when:
    branch:
      - main
    
    event:
      include:
      - push
   

- name: Notifiación-final
  image: drillster/drone-email
  settings:
    from: chavarria181386@unis.edu.gt    
    host: smtp.sendgrid.net
    port: 465
    username:
      from_secret: emu1
    password: 
      from_secret: emu2    
    subject: status pipeline 
    recipients:
        - gchavarriamunoz@gmail.com
        - jflores@unis.edu.gt
    body: El analisis sonarq indica que no pasa las quality gates 
    attachment: build-result.xml
  when:
    event:
      include:     
      - push
    status:      
    - failure
    - succes 
 

