kind: pipeline
type: docker
name: Integration


steps:
- name: build-war
  image: maven:3-jdk-11
  commands:
    - mvn -f ventas/pom.xml package 
- name: Servers
  image: alpine
  commands:
    - ls
    - cd ventas/target
    - ls
    - scp ventas-0.0.1-SNAPSHOT.war gab@gab-X541UAK:/Escritorio
    


   
   
