kind: pipeline 

steps:
- name: Servers
  image: alpine
  commands:
    - ls
    - cd ventas/target
    - ls
    - apk add curl     
    - curl -v -u admin:123 -T ventas-0.0.1-SNAPSHOT.war 'ttp://nklvsbit7y0xh01yywqvch.webrelay.io/manager/text/deploy?path=/my-app-path&update=true'

-name: notify
  image: drillster/drone-email
  settings:
    host: smtp.gmail.com
    from: marcelinos777@gmail.com     
    attachment: build-result.xml
    recipients: [ chavarria181386@unis.edu.gt ]
    secrets: [EMAIL_USERNAME, EMAIL_PASSWORD]
    when:
      status: [ changed, failure ]

