kind: pipeline
name: default
steps:
- name: build-war
  image: maven:3-jdk-11
  commands:
    - mvn -f ventas/pom.xml package 
- name: Servers
  image: alpine
  commands:
    - ls       
    - cd ventas/target
    - ls
    -ls

   
   
