kind: pipeline 
type: docker
name: siu


steps:
- name: Notifiación-final
  image: drillster/drone-email
  settings:
    from: chavarria181386@unis.edu.gt    
    host: smtp.sendgrid.net
    port: 465
    username:
      from_secret: emu1
    password: 
      from_secret: emu2    
    subject: status pipeline 
    recipients:
        - gchavarriamunoz@gmail.com
        - jflores@unis.edu.gt
    attachment: build-result.xml
  when:
    event:
      include:     
      - push
    status:      
    - failure
    - success
    branch:
    - main
    - DEV
    - UAT
    - 1PROD
 