kind: pipeline
name: default
steps:
- name: build-war
  image: maven:3-jdk-11
  commands:
    - mvn -f ventas/pom.xml package 
- name: Servers
  commands:
    - mv ventas-0.0.1-SNAPSHOT.war main-uat.war        
   
   
