kind: pipeline
type: docker
name: Integration


steps:
- name: build-war
  image: maven:3-jdk-11
  commands:
    - mvn -f ventas/pom.xml package 
- name: Servers
  image: alpine
  commands:
    - ls
    - cd ventas/target
    - ls
    - apk add curl
    - curl -v -u admin:admin -T 	ventas-0.0.1-SNAPSHOT.war 'http://localhost:8088/manager/text/deploy?path=/my-app-path&update=true'
    


   
   
