#Prueba
kind: pipeline
name: default
workspace:
  base: /Arquitectura
  path: https://github.com/Chavarria18/Arquitectura/ventas
steps:
- name: test
  image: maven:3-jdk-10
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
