node {
 def dockerHome = tool 'docker'
  env.PATH = "${dockerHome}/bin:${env.PATH}"
stage 'Checkout'
  checkout scm



 stage('unit-test') {
   try{
     
     
      def mvnHome =  tool name: 'M3', type: 'maven'                 
      echo "REALIZANDO LOS UNIT TESTS-2"
      echo "ahora"
      sh "ls"
      //sh "'${mvnHome}/bin/mvn test'"

 

     /* withMaven(maven: 'M3') {
            sh "mvn -f ventas/pom.xml test"
        }*/

   }catch(err){
     //emailext attachLog: false,body: 'Hubo un error en los unit test', subject: 'Jenkins-pipeline-status', to: 'gchavarriamunoz@gmail.com'
     //emailext attachLog: false,body: 'Hubo un error en los unit test', subject: 'Jenkins-pipeline-status', to: 'jflores@unis.edu.gt'

   }

    
        
    }
                     
                


  stage('SonarQube Analysis') {
    try{

        def mvnHome =  tool name: 'M3', type: 'maven'
        withSonarQubeEnv('sonarq') { 
          sh "ls"
          sh "ventas/mvn sonar:sonar -Dsonar.login=admin -Dsonar.password=tzec99"
        }

    }catch(err){
     // emailext attachLog: false,body: 'Hubo un error en sonarqube', subject: 'Jenkins-pipeline-status', to: 'gchavarriamunoz@gmail.com'

    }}
  
    

    stage('Build war') {
      try{ 
      def mvnHome =  tool name: 'M3', type: 'maven'       
      echo "REALIZANDO EL BUILD"
      //sh "${mvnHome}/bin/mvn package"
      withMaven(maven: 'M3') {
            sh "mvn -f ventas/pom.xml package"
        }

      }catch(err){
       // emailext attachLog: false,body: 'Hubo un error en el build', subject: 'Jenkins-pipeline-status', to: 'gchavarriamunoz@gmail.com'
      }
        
        
    } 
    

       stage('Server') {
      try{ 
        sh "ls"
        
        
        dir("ventas/target"){
   
          sh "docker cp ventas-0.0.1-SNAPSHOT.war tomcat1:/usr/local/tomcat/webapps" 

        }
        
        /*dir("ventas/target"){
           sh "java -jar -Dserver.port=8081 ventas-0.0.1-SNAPSHOT.jar"

        }*/ 
     
       


       /*withMaven(maven: 'M3') {
            sh "mvn -f ventas/pom.xml spring-boot:run"
        } */
   

     
      }catch(err){
       // emailext attachLog: false,body: 'Hubo un error en el build', subject: 'Jenkins-pipeline-status', to: 'gchavarriamunoz@gmail.com'
      }
        
        
    } 



}


